### ISSUE TITLE
scraper not working anymore

### ISSUE THREAD

**Issue by mjamei** [fdiazgon/mayoclinic-scrapper#1]
Have you tested this scraper recently? I cannot get it to run. it just returns an empty list.

**Comment by JoaquinSarro22** [comment]
I have the same question. Its still working?

**Comment by fediazgon** [comment]
Sorry, this was a toy project that I did long ago and that I'm not actively maintaining. If you want, you can create a PR and I'll gladly review it.

**Comment by rzsgrt** [comment]
I want to scrape information from mayo clinic and found this repo. and got same result,empty.

Things I try:
First, start url edited to `https://www.mayoclinic.org/diseases-conditions/index?letter={all letter}`
but still I got empty result. Then I try to ask gpt and answer is
```
The website might be blocking the spider: Some websites implement measures to prevent web scraping, 
such as blocking bots based on their user-agent or IP address. 
Make sure you are using a valid user-agent and that the website allows web scraping.
```

So, I check web again and find this:
<img width="1186" alt="image" src="https://github.com/fediazgon/mayoclinic-scrapper/assets/47804549/c6b045e8-0bc5-405a-ab82-9e6ed2bc99f1">

I think it means we can scrape from this web.

Also, I think maybe links on https://github.com/fediazgon/mayoclinic-scrapper/blob/50859f94e6af9fd6b4021e68c538fa7f28ab6384/scraper.py#L56 should be updated

**Comment by fediazgon** [comment]
If that's the case I'll just archive the repo or add a note to the README. This was started as a University project to show the capabilities of Neo4J.

**Comment by rzsgrt** [comment]
yes. you can link to this ToS https://www.mayoclinicplatform.org/terms-of-use/
